### ISSUE TITLE
How much GPU memory did nppac require during pretrain-stage?

### ISSUE THREAD

**Issue by nuomizai** [conglu1997/nppac#1]
When I tried to run paper_clone_gp.sh locally by removing the exp_scripts/run-gpy.sh, I got a 'CUDA out of memory' error.
My command is as follows:
```
gpu_id=0
env_name=door
data_set='expert_demonstration_data/door2_sparse.npy'
kt=matern12
python nppac/clone_from_dataset_gp.py --name $env_name --save_policies --data_set $data_set \
    --use_gpu --use_ard --gp_rank 1 --kernel_type $kt --save_dir $env_name
```

Then I got an out-of-memory error as:
```
RuntimeError: CUDA out of memory. Tried to allocate 131.26 GiB (GPU 0; 23.70 GiB total capacity; 1.87 GiB already allocated; 14.61 GiB free; 2.56 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

This error happened at line 50 in clone_from_dataset_gp.py as
`observed_pred = likelihood(model(o_torch))`
where the o_torch.size() is only [1, 39]

I'd like to know is this script able to run with a 20GB GPU locally. Or is there something wrong with the settings in the script? Thank you!

**Comment by conglu1997** [comment]
Hey, this should be manageable with only 5GB of memory - I would check torch and gpytorch versions and make sure 

`with torch.no_grad(), gpytorch.settings.fast_pred_var():`

is working :)

**Comment by nuomizai** [comment]
> Hey, this should be manageable with only 5GB of memory - I would check torch and gpytorch versions and make sure
> 
> `with torch.no_grad(), gpytorch.settings.fast_pred_var():`
> 
> is working :)

Thank you, I found it due to the version of gpytorch. I've tried the versions in `https://readthedocs.org/projects/gpytorch/` one by one and found the version 1.4.2 works! I installed gpytorch by 

```
pip install gpytorch==1.4.2
```
